# MAKEFILE for capture 4
# 4.1
#p4.1.out:p4.1.c
#	gcc -g p4.1.c -o p4.1.out

#4.2
#p4.2.out:p4.2.c squareApproach.o calPrime.o
#	gcc -g p4.2.c  calPrime.o squareApproach.o -o p4.2.out


#calPrime.o:calPrime.c squareApproach.o
#	gcc -c calPrime.c  -o calPrime.o

#squareApproach.o:squareApproach.c 
#	gcc -c squareApproach.c 

#4.3
#p4.3.out:p4.3.c triangle.o
#	gcc -g p4.3.c triangle.o -o p4.3.out

#triangle.o:triangle.c
#	gcc -c triangle.c

#4.4
p4.4.out:p4.4.c copy_n.o
	gcc -g p4.4.c copy_n.o -o p4.4.out

copy_n.o:copy_n.c
	gcc -g -c copy_n.c
